Fix an error in handling status code 409
Error:

{"errors": "Payment couldn't be completed because: lock expired"}
1640.6050653457642
409 encountered, opening channel
Traceback (most recent call last):
  File "dev/consumer.py", line 82, in <module>
    print("409 encountered, opening channel")
TypeError: unsupported operand type(s) for *: 'function' and 'int'
Makefile:18: recipe for target 'consumer' failed
make: *** [consumer] Error 1